Check backend + tests
Tristan-H11/Kryptographie pull request #140
Opened 2024-05-05 14:25 UTC by Felefix201

Testfälle + Angepasste Kommentare + kleinere Funktionsanpassungen / erweiterungen / Errorhandling im Backend

2024-05-07 09:04 UTC, Tristan-H11 requested changes

2024-05-07 09:04 UTC, Tristan-H11 commented on src/math_core/ecc/secure_finite_field_elliptic_curve.rs
> +    fn test_has_point_on_curve_with_negative_a() {
hier wird nicht mit einem negativen a, sondern mit einem negativen n getestet. Unser a ist immer negativ, weil wir ja -(n^2) rechnen.

2024-05-07 09:04 UTC, Tristan-H11 commented on src/math_core/ecc/secure_finite_field_elliptic_curve.rs
>          // (5, 8) liegt auf y^2 = x^3 + 7 (mod 17)
irreführender Kommentar, weil ja jedes mal neue Kurven generiert werden

2024-05-07 09:04 UTC, Tristan-H11 commented on src/math_core/ecc/secure_finite_field_elliptic_curve.rs
>          // (5, 8) liegt auf y^2 = x^3 + 7 (mod 17)
s.o.

2024-05-07 09:04 UTC, Tristan-H11 commented on src/math_core/number_theory/extended_euclid_result.rs
> +mod tests {
Die Tests zu equality und inequality sind ganz süß und löblich, aber eigentlich nicht notwendig, weil diese Eigenschaften ja aus der Komposition der Typen, aus denen ECResult zusammengesetzt ist, abgeleitet werden. 
Streng genommen, sind die also nicht im Testscope dieser Unit (Unit-Tests). Können trotzdem drin bleiben, weil die ja nichts tun. Aber an sich sind die nicht notwendig/zielführend :D

2024-05-15 18:28 UTC, Felefix201 commented on src/encryption/core/menezes_vanstone/keys.rs
> +        let x = mv_private_key.x.parse().unwrap(); // TODO: Anstatt .unwrap() ggf. turbofish verwenden ? --> z.B. .parse()::<BigInt>()
check

2024-05-15 18:28 UTC, Felefix201 commented on src/encryption/core/menezes_vanstone/menezes_vanstone_scheme.rs
> +        let random_seed:u16 = rng.next_u32() as u16;
check

2024-05-15 18:28 UTC, Felefix201 commented on src/encryption/core/menezes_vanstone/menezes_vanstone_scheme.rs
> +        assert!(result.is_err());
check

2024-05-15 18:28 UTC, Felefix201 commented on src/encryption/core/menezes_vanstone/menezes_vanstone_scheme.rs
> +        assert!(result.is_err());
check

2024-05-15 18:29 UTC, Felefix201 commented on src/math_core/ecc/secure_finite_field_elliptic_curve.rs
> +        let point_at_infinity = FiniteFieldEllipticCurvePoint::new(BigInt::zero(), BigInt::zero());
check

2024-05-15 18:29 UTC, Felefix201 commented on src/math_core/ecc/secure_finite_field_elliptic_curve.rs
> +    fn test_has_point_on_curve_with_negative_a() {
check

2024-05-15 18:29 UTC, Felefix201 commented on src/math_core/ecc/secure_finite_field_elliptic_curve.rs
>          // (5, 8) liegt auf y^2 = x^3 + 7 (mod 17)
check

2024-05-15 18:29 UTC, Felefix201 commented on src/math_core/ecc/secure_finite_field_elliptic_curve.rs
>          // (5, 8) liegt auf y^2 = x^3 + 7 (mod 17)
check

2024-05-15 18:29 UTC, Felefix201 commented on src/math_core/number_theory/extended_euclid_result.rs
> +mod tests {
jao das sind sie xD

2024-05-16 10:16 UTC, merged